2019-02-18T05:24:05.827Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'WarehouseWest1' in collection with ID 'Asset:delivery.Product' does not exist)
    at /home/q3/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2019-02-18T05:24:05.984Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'WarehouseWest1' in collection with ID 'Asset:delivery.Product' does not exist)
    at /home/q3/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2019-02-18T05:24:05.985Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Object with ID 'WarehouseWest1' in collection with ID 'Asset:delivery.Product' does not exist)\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Object with ID 'WarehouseWest1' in collection with ID 'Asset:delivery.Product' does not exist)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Object with ID 'WarehouseWest1' in collection with ID 'Asset:delivery.Product' does not exist)\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Object with ID 'WarehouseWest1' in collection with ID 'Asset:delivery.Product' does not exist)\n\n    at _initializeChannel.then.then.then.then.catch (/home/q3/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2019-02-18T05:29:38.470Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: ReferenceError: identifier 'customer' undefined)
    at /home/q3/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2019-02-18T05:29:38.471Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: ReferenceError: identifier 'customer' undefined)
    at /home/q3/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2019-02-18T05:29:38.472Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: ReferenceError: identifier 'customer' undefined)\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: ReferenceError: identifier 'customer' undefined)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: ReferenceError: identifier 'customer' undefined)\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: ReferenceError: identifier 'customer' undefined)\n\n    at _initializeChannel.then.then.then.then.catch (/home/q3/.nvm/versions/node/v8.12.0/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
